(function () {
  const root = document.getElementById('app'); if (!root) return;
  const safe = (value) => String(value ?? '').replace(/[&<>"']/g, (c) => ({ '&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;' })[c]);
  const render = (content) => { root.innerHTML = `<main class="backend-gate" dir="rtl">${content}</main>`; };
  const login = () => render(`<section class="backend-gate__panel"><i class="ph ph-shield-check backend-gate__icon" aria-hidden="true"></i><h1>بده‌بستان</h1><p>برای مدیریت تعهدها وارد شوید.</p><form id="magic-link-form" novalidate><label for="magic-email">ایمیل</label><input id="magic-email" name="email" inputmode="email" autocomplete="email" required><p id="magic-error" class="field-error" role="alert"></p><button class="btn btn-primary" type="submit">ارسال لینک ورود</button></form></section>`);
  const unavailable = () => render(`<section class="backend-gate__panel"><i class="ph ph-plugs-connected backend-gate__icon" aria-hidden="true"></i><h1>اتصال سرویس لازم است</h1><p>مقادیر عمومی Supabase را در <code>runtime-config.js</code> یا متغیرهای Vite قرار دهید.</p></section>`);
  const amount = (value) => value ? `${Number(value).toLocaleString('fa-IR')} ریال` : '';
  const dashboard = (data) => {
    const records = data.records || [];
    const cards = records.map((record) => { const activeLink = record.share_links?.find((link) => !link.revoked_at); return `<article class="backend-record"><div><strong>${safe(record.title)}</strong><span>${record.kind === 'item' ? 'امانت' : record.kind === 'money' ? 'قرض' : 'دنگ'}</span></div><div>${amount(record.amount)}${record.payment_cards?.[0] ? `<small>•••• ${safe(record.payment_cards[0].last4)}</small>` : ''}</div><div class="backend-record__actions"><button class="btn btn-ghost" data-share="${record.id}"><i class="ph ph-share-network" aria-hidden="true"></i> اشتراک‌گذاری</button>${activeLink ? `<button class="btn btn-ghost" data-revoke="${activeLink.id}"><i class="ph ph-link-break" aria-hidden="true"></i> غیرفعال‌سازی</button>` : ''}</div></article>`; }).join('') || `<p class="empty-state">هنوز موردی ثبت نشده است.</p>`;
    render(`<section class="backend-dashboard"><header><div><h1>تعهدها</h1></div><button class="btn btn-primary" id="new-record"><i class="ph ph-plus" aria-hidden="true"></i> ثبت جدید</button></header><div class="backend-records">${cards}</div><button class="btn btn-ghost" id="load-notifications"><i class="ph ph-bell" aria-hidden="true"></i> اعلان‌ها</button></section>`);
  };
  const newRecord = () => render(`<section class="backend-gate__panel"><button class="btn btn-ghost" id="back-dashboard"><i class="ph ph-arrow-right" aria-hidden="true"></i> بازگشت</button><h1>ثبت جدید</h1><form id="record-form" novalidate><label>نوع<select name="kind"><option value="item">امانت</option><option value="money">قرض پول</option><option value="expense">دنگ</option></select></label><label>عنوان<input name="title" required maxlength="160"></label><label>طرف مقابل<input name="recipientName" required maxlength="80"></label><label>مبلغ<input name="amount" inputmode="numeric"></label><label>موعد<input name="dueAt" type="date"></label><label>شماره کارت<input name="cardNumber" inputmode="numeric" autocomplete="off"></label><label>یادداشت<textarea name="notes" maxlength="2000"></textarea></label><p id="record-error" class="field-error" role="alert"></p><button class="btn btn-primary" type="submit"><i class="ph ph-plus" aria-hidden="true"></i> ثبت</button></form></section>`);
  const shared = async (token) => { try { const data = await window.BedehBackend.shared(token); const record = data.record; render(`<section class="backend-gate__panel"><h1>${safe(record.title)}</h1><p>${amount(record.amount)}${record.card ? `<br><bdi>${safe(record.card.number)}</bdi></p><button class="btn btn-secondary" data-copy-card="${safe(record.card.number)}"><i class="ph ph-copy" aria-hidden="true"></i> کپی شماره کارت</button>` : '</p>'}<button class="btn btn-primary" data-confirm-receipt="${safe(token)}"><i class="ph ph-check-circle" aria-hidden="true"></i> تأیید دریافت</button><p id="shared-result" role="status"></p></section>`); } catch (error) { render(`<section class="backend-gate__panel"><i class="ph ph-link-break backend-gate__icon" aria-hidden="true"></i><h1>لینک در دسترس نیست</h1><p>${safe(error.message)}</p></section>`); } };
  const begin = async () => {
    if (!window.BedehBackend?.configured) return unavailable();
    const match = location.hash.match(/^#share\/([A-Za-z0-9_-]{43})$/); if (match) return shared(match[1]);
    const user = await window.BedehBackend.session(); if (!user) return login();
    try { dashboard(await window.BedehBackend.command('dashboard')); } catch (error) { render(`<section class="backend-gate__panel"><h1>بارگذاری نشد</h1><p>${safe(error.message)}</p><button class="btn btn-secondary" id="retry-backend">تلاش دوباره</button></section>`); }
  };
  document.addEventListener('submit', async (event) => {
    if (event.target.id === 'magic-link-form') { event.preventDefault(); const error = document.getElementById('magic-error'); const button = event.target.querySelector('button'); button.disabled = true; button.textContent = 'در حال ارسال…'; error.textContent = ''; try { await window.BedehBackend.sendMagicLink(new FormData(event.target).get('email')); button.textContent = 'لینک ورود ارسال شد'; } catch (err) { error.textContent = err.message; button.disabled = false; button.textContent = 'ارسال لینک ورود'; } }
    if (event.target.id === 'record-form') { event.preventDefault(); const form = new FormData(event.target); const button = event.target.querySelector('button'); const error = document.getElementById('record-error'); const payload = Object.fromEntries([...form.entries()].filter(([, value]) => String(value).trim())); button.disabled = true; button.textContent = 'در حال ثبت…'; error.textContent = ''; try { await window.BedehBackend.command('create-record', payload); await begin(); } catch (err) { error.textContent = err.message; button.disabled = false; button.textContent = 'ثبت'; } }
  });
  document.addEventListener('click', async (event) => {
    const target = event.target.closest('button'); if (!target) return;
    if (target.id === 'retry-backend' || target.id === 'back-dashboard') return begin();
    if (target.id === 'new-record') return newRecord();
    if (target.id === 'load-notifications') { try { const data = await window.BedehBackend.command('notifications'); alert((data.notifications || []).map((notice) => notice.body).join('\n') || 'اعلانی ندارید.'); } catch (err) { alert(err.message); } }
    if (target.dataset.share) { target.disabled = true; try { const result = await window.BedehBackend.command('create-share-link', { recordId: target.dataset.share }); const url = `${location.origin}${location.pathname}#share/${result.token}`; await navigator.clipboard?.writeText(url); target.innerHTML = '<i class="ph ph-check" aria-hidden="true"></i> کپی شد'; } catch (err) { target.disabled = false; alert(err.message); } }
    if (target.dataset.revoke) return render(`<section class="backend-gate__panel" role="dialog" aria-modal="true" aria-labelledby="revoke-title"><i class="ph ph-warning-circle backend-gate__icon" aria-hidden="true"></i><h1 id="revoke-title">غیرفعال‌سازی لینک</h1><p>طرف مقابل فوراً دسترسی به این لینک و شماره کارت را از دست می‌دهد. این عمل بازگشت‌پذیر نیست.</p><button class="btn btn-danger" data-confirm-revoke="${target.dataset.revoke}">غیرفعال‌سازی لینک</button><button class="btn btn-ghost" id="back-dashboard">انصراف</button></section>`);
    if (target.dataset.confirmRevoke) { target.disabled = true; try { await window.BedehBackend.command('revoke-share-link', { linkId: target.dataset.confirmRevoke }); await begin(); } catch (err) { target.disabled = false; alert(err.message); } }
    if (target.dataset.copyCard) { await navigator.clipboard?.writeText(target.dataset.copyCard); target.innerHTML = '<i class="ph ph-check" aria-hidden="true"></i> کپی شد'; }
    if (target.dataset.confirmReceipt) { try { await window.BedehBackend.recipient(target.dataset.confirmReceipt, 'confirm-receipt'); document.getElementById('shared-result').textContent = 'دریافت تأیید شد'; target.disabled = true; } catch (err) { document.getElementById('shared-result').textContent = err.message; } }
  });
  begin();
}());
